project_name: google-mcp-server

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    binary: google-mcp-server

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    files:
      - README.md
      - LICENSE
      - config.example.json

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: "^feat"
    - title: Bug Fixes
      regexp: "^fix"
    - title: Performance
      regexp: "^perf"
    - title: Refactor
      regexp: "^refactor"

release:
  github:
    owner: ngs
    name: google-mcp-server
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}}-v{{.Version}}"
  header: |
    ## Google MCP Server Release

    Model Context Protocol server for Google APIs integration.

nfpms:
  - maintainer: Atsushi Nagase <a@ngs.io>
    description: MCP server for Google APIs (Calendar, Drive, Gmail, Photos, Sheets, Docs)
    homepage: https://github.com/ngs/google-mcp-server
    license: MIT
    formats:
      - deb
      - rpm
      - apk

brews:
  - name: google-mcp-server
    homepage: https://github.com/ngs/google-mcp-server
    description: MCP server for Google APIs integration
    license: MIT
    repository:
      owner: ngs
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    folder: Formula
    test: |
      system "#{bin}/google-mcp-server", "--version"
    install: |
      bin.install "google-mcp-server"